-- Create database and role (run as postgres superuser)
-- Adjust passwords and IPs as needed.
CREATE DATABASE "user-account";
CREATE USER appuser WITH ENCRYPTED PASSWORD 'P@55Word';
GRANT ALL PRIVILEGES ON DATABASE "user-account" TO appuser;
\c user-account
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(10, 2) NOT NULL,
    course VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    fees_status VARCHAR(255) CHECK (fees_status IN ('Paid', 'Unpaid', 'Half_paid')),
    name VARCHAR(255) NOT NULL
);
GRANT SELECT, INSERT, UPDATE, DELETE ON users TO appuser;
